pool:
  vmImage: 'Ubuntu 16.04'

variables:
  Version: '3.0.$(Build.BuildId)'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: '**/*.csproj'
    feedsToUse: 'select'
    verbosityRestore: 'minimal'
    vstsFeed: 'BW'

- task: DotNetCoreCLI@2
  inputs:
    command: custom
    custom: publish
    publishWebProjects: false
    zipAfterPublish: false
    arguments: '--no-restore -c Release --output ./publish'
    projects: '**/*.csproj'

- script: |
    docker build -f src/BioEngine.BRC.API/Dockerfile src/BioEngine.BRC.API/publish -t biowareru/BioEngine.BRC.API:$(Version)
  displayName: 'build docker image'
  
- script: |
    docker login -u $(dockerId) -p $(dockerPswd)
  displayName: 'login to docker hub'

- script: |
    docker push biowareru/BioEngine.BRC.API:$(Version)
  displayName: 'push image to docker hub'
    