pool:
  vmImage: 'Ubuntu 16.04'

variables:
  Version: '3.0.$(Build.BuildId)'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: '**/*.csproj'
    feedsToUse: 'select'
    verbosityRestore: 'minimal'
    vstsFeed: 'BW'

- task: DotNetCoreCLI@2
  inputs:
    command: custom
    custom: publish
    arguments: '--no-restore -c Release --output ./publish'
    projects: '**/*.csproj'

